version: "3.8"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compro_sena_view
    volumes:
      - .:/var/www
      - /var/www/vendor
    ports:
      - "6060:8000"
